### ISSUE TITLE
After removing items from a group, not all items in the form "Предмети для груп" are added after clicking on the "Призначити" button

### ISSUE THREAD

**Issue by MakcSas** [chdtu-fitis/deanoffice-frontend#126]
Description: After removing items from a group, not all items in the form "Предмети для груп" are added after clicking on the "Призначити" button

Steps To Reproduce:
1. Open http://localhost:4200
2. Go to form "Предмети для груп"
3. Selected group and semester
4. No course have been selected for the group
5. Select more than one course and click the button "Призначити"
6. Select all course in courses for group table and click the button "Видалити"
7. Select one more course  and click the button "Призначити"

Actual result: not all course are added to the group
Expected result: all course are added to the group

Additional Information: https://www.dropbox.com/s/4xh4qf95imeiapk/Add%20course%20in%20to%20a%20groupa.webm?dl=0

**Comment by andriyor** [comment]
Після натискання кнопки "Призначити" з обраних курсів мають прибратися відмітки
