### ISSUE TITLE
Button "Редагувати курс" inactive on form "Предмети для груп" after after assigning an item to a group

### ISSUE THREAD

**Issue by MakcSas** [chdtu-fitis/deanoffice-frontend#127]
Description: Button "Редагувати курс" inactive on form "Предмети для груп" after after assigning an item to a group

Steps To Reproduce: 
1. Open http://localhost:4200
2. Go to form "Предмети для груп"
3. Selected group and semester
4 Select course
5. Click the button "Призначити"

Actual result: Button "Редагувати курс" inactive, but clicking to the right of the button opens course editing window
Expected result: Button "Редагувати курс" active

Additional Information: https://www.dropbox.com/s/r26l725kwm0ipo7/Button%20%27%27%D0%A0%D0%B5%D0%B4%D0%B0%D0%B3%D1%83%D0%B2%D0%B0%D1%82%D0%B8%20%D0%BA%D1%83%D1%80%D1%81%27%27%20inactive.webm?dl=0

**Comment by gzaspa** [comment]
Робота функції збилась пвсля правки. Це не баг, це особливість роботи програми. Тому потрібно повернути дану річ назад. Редагувати парметри курсу не повинно бути можливо, якщо предмети для групи не збережено. Дуже важливо перевіряти роботу функції після внесення правок - ця функція в даний час працює з явними помилками.
