### ISSUE TITLE
Changes to the course are saved on the form "Предмети для груп" after pressing the "Відмінити зміни" button

### ISSUE THREAD

**Issue by MakcSas** [chdtu-fitis/deanoffice-frontend#128]
Description: Changes to the course are saved on the form "Предмети для груп" after pressing the "Відмінити зміни" button

Steps To Reproduce: 
1. Open http://localhost:4200
2. Go to form "Предмети для груп"
3. Selected group and semester
4. Click the button "Редагувати курс"
5. Enter course and enter hours
6. Choose the number of credits and select a rating form
7. Click the button "Відмінити зміни"

Actual result: Changes saved
Expected result: Changes not saved

Additional Information: https://www.dropbox.com/s/axjtqpcypwrgwsk/%D0%A0%D0%B5%D0%B4%D0%B0%D0%B3%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D1%83%20%D0%B2%20%D0%B3%D1%80%D1%83%D0%BF%D1%96%20%28%D0%92%D1%96%D0%B4%D0%BC%D1%96%D0%BD%D0%B8%D1%82%D0%B8%20%D0%B7%D0%BC%D1%96%D0%BD%D0%B8%29.webm?dl=0

**Comment by gzaspa** [comment]
Це не помилка, а особливість роботи програми
