### ISSUE TITLE
Працівник деканату може копіювати призначені предмети з групи в групу з семестрами, що відрізняються

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#130]
В системі вже є функція в вікні "Предмети для груп", яка дає можливість копіювати призначені предмети з групи в групу в рамках одного семестру. Потрібно зробити те ж, але для копіювання в інші семестри.

**Comment by freedbrd** [comment]
Доброго дня.

Вибачте, що вчасно не повідомив вас, але на цьому тижні я не зможу до вас
підійти, оскільки цілий тиждень мене де буде в Черкасах.

Є питання з приводу бек-енд частини, справа в тому,  що воно не хоче
копмілюватись.
[image: image.png]

Я так розумію, що помилка десь в коді програми.

чт, 13 сент. 2018 г. в 15:34, Grygoriy Zaspa <notifications@github.com>:

**Comment by gzaspa** [comment]
Напишіть адресу своєї електронної пошти

**Comment by freedbrd** [comment]
vadimtrihleb@gmail.com

пн, 17 сент. 2018 г. в 17:43, Grygoriy Zaspa <notifications@github.com>:
