### ISSUE TITLE
Працівник деканату може переглядати інформацію про групи студентів у зручному для нього вигляді (епік #12)

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#136]
Стосується вікна груп (пункт меню Початок року - Групи)
1. Зробити таблицю красивою
2. Додати в неї спеціальність
3. Можливо, відмовитись від компоненту таблиці, що використовується, з метою спрощення роботи з таблицею та збільшення швидкості роботи. В такому разі потрібно зберегти багатоколонкове сортування

**Comment by yamadote** [comment]
Потрібно виправити відображення символ сортування в наступному спринті
