### ISSUE TITLE
Працівник деканату може додавати, редагувати та видаляти групи (епік #12)

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#137]
Зробити за аналогією з вікном спеціалізацій
При видаленні групи перевіряти, чи є в даній групі активні студенти; якщо є, не давати змоги видалити

**Comment by gzaspa** [comment]
Побачив недолік в 'add-group': багато логіки в конструкторі.
"Don't fetch data in a component constructor. You shouldn't worry that a new component will try to contact a remote server when created under test or before you decide to display it. Constructors should do no more than set the initial local variables to simple values."
https://angular.io/guide/lifecycle-hooks

**Comment by gzaspa** [comment]
і в update-group.component.ts так само

**Comment by gzaspa** [comment]
В заголовку таблиці (колонка 2) потрібно написати Освітня програма (спеціалізація)

**Comment by gzaspa** [comment]
У вікні додавання групи в комбобоксі спеціалізацій зроблено сортування за id - це не правильно. Сортування потрібно робити за кваліфікацією+спеціальність+алфавіт. І це краще зробити на бекенді

**Comment by yamadote** [comment]
Потрібно зробити валідацію даних і добавити обробку відправленого запросу для видалення
