### ISSUE TITLE
Працівник деканату може бачити в вікні "Закінчити навчальний рік" список груп які випускаються в цьому році

### ISSUE THREAD

**Issue by andriyor** [chdtu-fitis/deanoffice-frontend#197]
Список груп поділяється на ступені та форми навчання
Всі групи обрані за замовчуванням
Кнопка для отримання студентів з обраних груп

**Comment by gzaspa** [comment]
Приклад цього вікна в старій програмі
![image](https://user-images.githubusercontent.com/16689707/54116881-5d6ebe80-43f8-11e9-9999-83e505653848.png)
