### ISSUE TITLE
Працівник деканату може переглядати інформацію про викладачів, що належать до кафедр його факультету

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#225]
Пов'язано з issue #235 бекенду

**Comment by evlans** [comment]
А якщо викладач на одній кафедрі штатний працівник, а на іншій сумісник, і кафедри на різних факультетах?

**Comment by gzaspa** [comment]
> А якщо викладач на одній кафедрі штатний працівник, а на іншій сумісник, і кафедри на різних факультетах?

Викладач повинен бути введений і прикріплений до кафедри на тому факультеті, де його основне місце роботи. А коли іде прикріплення викладача до предмета, то там показуються всі викладачі, незалежно від факультету. Більше ніде викладач в системі не фігурує, поки що.
