### ISSUE TITLE
Предмети для груп: Не завжди зберігається дата іспиту

### ISSUE THREAD

**Issue by OlexanderPustovit** [chdtu-fitis/deanoffice-frontend#232]
Якщо для предмету не вибраний викладач, то дата іспиту не збережеться після натискання кнопки "Зберегти"

Кроки для відтворення:
1. Відкрити розділ "Предмети для груп".
2. Вибрати групу та семестр.
3. Вибрати предмет із списку.
4. Натиснути "Призначити".
5. Вибрати для предмету дату іспиту (не вибирати викладача!).
6. Натиснути "Зберегти".
7. Перезавантажити сторінку та вибрати ту ж групу і семестр.

Результат: дата іспиту не обрана.
Очікуваний результат: предмет має дату іспиту.

Відтворення: https://youtu.be/0YKmBuqMR5E

**Comment by gzaspa** [comment]
Already fixed
