### ISSUE TITLE
Предмети для груп: дата не зберігається при виборі іншого семестру

### ISSUE THREAD

**Issue by andriyor** [chdtu-fitis/deanoffice-frontend#251]
Кроки для відтворення:

Відкрити розділ "Предмети для груп".
Вибрати групу.
Обрати інший семестр (не перший, а якийсь інший)
Вибрати для предмету дату 
Натиснути "Зберегти".

Результат: дата іспиту не обрана.
Очікуваний результат: предмет має дату іспиту.
Можна виставити дату з другого разу.

**Comment by gzaspa** [comment]
Щось дуже сумнівна послідовність кроків, що призводить до помилки: вона означає, що дату ніколи не можна поставити.
