### ISSUE TITLE
Працівник деканату по роботі з іноземними студентами може перевірити на співпадіння предмети своїх груп з предметами відповідних груп інших факультетів

### ISSUE THREAD

**Issue by gitdmelnick** [chdtu-fitis/deanoffice-frontend#254]
* [x] Створити сервіс для отримання об'єкту з групами та предметами
* [x] При натисканні відповідної кнопки відобразити ці данні у вигляді таблиці

**Comment by BlackMaizeGod** [comment]
* [x ] Створити сервіс для отримання об'єкту з групами та предметами
* [] При натисканні відповідної кнопки відобразити ці данні у вигляді таблиці
