### ISSUE TITLE
Працівник деканату може додавати, видаляти та редагувати інформацію про викладачів в системі

### ISSUE THREAD

**Issue by gitdmelnick** [chdtu-fitis/deanoffice-frontend#255]
# Buttons
- [x] **Add teacher;**
- [x]  **Update teacher;**
- [x] **Delete teacher;**

**Comment by BlackMaizeGod** [comment]
# Buttons
- [] *Add teacher;*
- []  *Update teacher;*
- [] *Delete teacher;*
