### ISSUE TITLE
Предмети для груп: Не завжди зберігається дата іспиту

### ISSUE THREAD

**Issue by OlexanderPustovit** [chdtu-fitis/deanoffice-frontend#258]
Дата іспиту не зберігається, якщо фокус був на полі вибору дати.

Кроки для відтворення:
1. Відкрити розділ "Предмети для груп".
2. Вибрати групу та семестр.
3. Натиснути на поле для вибору дати іспиту.
4. Ввести дату іспиту з клавіатури.
5. Натиснути кнопку "Зберегти".

Результат: дата іспиту не обрана.
Очікуваний результат: дата іспиту збережена.

Відтворення: https://youtu.be/5lAwv2z0EbE

**Comment by andriyor** [comment]
Duplicate issue #251

**Comment by andriyor** [comment]
Duplicate of #251
