### ISSUE TITLE
Працівник деканату може сформувати документ з аркушем успішності студента ("бігунком") для багатьох студентів/предметів одночасно

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#335]
Реалізувати функцію у вікні оцінок, зробивши набір студентів/предметів, вибраних для формування бігунка,  за аналогією з кошиком в інтернет-магазинах

**Comment by eyarijk** [comment]
Гілка [335-new-feature/produce-document-with-students-achievement-sheet](https://github.com/chdtu-fitis/deanoffice-frontend/tree/335-new-feature/produce-document-with-students-achievement-sheet)
