### ISSUE TITLE
Адміністратор може змерджити назви предметів, які являють собою фактично одну назву

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#373]
#236 на бекенді

**Comment by volodymyr-polishchuk** [comment]
Привіт всім. 

Я дослідив цю задачу і знайшов наступне:

1. Ця задача залежить від задачі https://github.com/chdtu-fitis/deanoffice-frontend/issues/375

2. Для роботи функціоналу задачі на бекенд частині вже створенний endpoint `/merge`. Щоб змержити предмети потрібно зробити POST запит на `/merge` і передати дані у форматі `Map<Integer, List<Integer>>`, в якому **key** - це правильний **id**, а **value** - список неправильних **id**. 
Для прикладу у форматі JSON це буде виглядати наступним чином:
```
{
  "16": [
    13, 14, 15
  ],
  "17": [
    18, 19 
  ]
}
```
Де 16 та 17 це id предметів з правильними назвами. А `13, 14, 15` - це id предметів з неправильними назвами предметів для предмету з id 16. `18, 19` - це id предметів з неправильними назвами для предмету з id 17, відповідно.

3. Поточна реалізація для відображення предметів зі схожими назвами виглядає як зображено далі:
![image](https://user-images.githubusercontent.com/35197419/71548475-647eb180-29b7-11ea-873a-e8538f78426f.png)
Пропоную вдосконалити існуючий інтерфейс і добавити радіо кнопки для вибору правильної назви предмету, а також чекбокси для вибору предметів, які потрібно змерждити. Для підтвердження потрібно добавити контролюючу кнопку. Весь макет можна побачити на рисунку далі:
![image](https://user-images.githubusercontent.com/35197419/71548497-baebf000-29b7-11ea-9395-9b2fcbf53e67.png)
Додатково добавити реакцію на дії користувача, а саме при зміні вибору правильного предмету - знімати вибір з всіх предметів для мерджу. Для предмету, який обраний як правильний, блокувати чекбокс на позиції виключений, Якщо жодного предмету не обрано, то блокувати кнопку для мерджу. Всі іконки потрібно супроводжувати підказками при наведенні.

За попередніми оцінками час виконання задачі: 3 години

**Comment by gzaspa** [comment]
Гарно написано

**Comment by volodymyr-polishchuk** [comment]
Привіт всім. 

Я реалізував цю задачу. Було змінено інтерфейс схожих предметів. Було добавлено контролери для вибору предмету з правильною назвою та предметів, які потрібно з'єднати з предметом з правильною назвою. Зараз інтерфейс виглядає як показано на рисунку нижче: 
![image](https://user-images.githubusercontent.com/35197419/73594774-13179400-451a-11ea-808f-2d9fad3f42de.png)
Якщо змінити головний предмет, то автоматично обираються всі інші предмети. Якщо прийняти вибір з всіх предметів, то кнопка з'єднання предметів блокується.
![image](https://user-images.githubusercontent.com/35197419/73594806-68ec3c00-451a-11ea-8847-84934ec27ff2.png)

Для цієї задачі також був створений pull request: https://github.com/chdtu-fitis/deanoffice-frontend/pull/396

**Comment by ombogdan** [comment]
Title: Не можу змерджить предмети
Platform: Google Chrome version 81.0.4, Windows 10Pro
Summary: Коли я пробую змерджиь предмети з ID 63 і 65 нічого не відбувається
Steps to reproduse:
1. Зайти на сайт під роллю адміна
2. Перейти на сторінку адміністрування, схожі предмети
3. З'єднати предмети 63 і 65
Expected result: предмети будуть зєднані
Actual result: Нічого не відбувається
Priority: 3
Severity: Major

**Comment by ombogdan** [comment]
Title: Після зєднання предмети обидва предмети відображаються на сторінці предмети
Platform: Google Chrome version 81.0.4, Windows 10Pro
Summary: Коли я пробую з'єднати предмети з ID 110 і 114  то вони пропадають з сторінки "Схожі предмети" але відображаються на сторінці "Предмети"
Steps to reproduse:
1. Зайти на сайт під роллю адміна
2. Перейти на сторінку адміністрування, схожі предмети
3. З'єднати предмети 110 і 114 вибравши за основний 110
4. Перейти на сторінку "Предмети"
5. В пошуку ввести "Вступ до мережних технологій"
Expected result: Предмет не буде знайдений
Actual result: Предмет знайдений
Priority: 2
Severity: Critical
