### ISSUE TITLE
Адміністратор може переглянути та виправити список предметів, в яких неправильно виставлена кількість кредитів

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#374]
#231 на бекенді

**Comment by volodymyr-polishchuk** [comment]
Привіт всім! 

Я дослідив цю задачу і знайшов наступне:

1. Для отримання списку предметів, в яких не правильно виставляна кількість кредитів, потрібно зробити GET запит на ендпоінт `/credits/wrong`. У відповідь буде надано список із предметів в наступному форматі:
```
[
  {
    "id": 1,
    "courseName": {
      "id": 2,
      "name": "Назва предмету",
      "nameEng": "Назва на англійській"
    },
    "semester": 0,
    "knowledgeControl": {
      "id": 3,
      "name": "Тип контролю (залік, екзамен і т.п.)"
    },
    "hours": 50,
    "credits": 1,
    "hoursPerCredit": 30
  },
  {
     ...
  }
]
```

2. Встановлення кількості кредитів на правильні відбувається автоматично. Потрібно лише відправити PUT запит на ендпоінт `/credits/wrong` і в тілі запиту вказати список з id предметів, які потрібно виправити.

Для реалізації цієї задачі я пропоную в пункт Адміністрування додати підпункт Виправлення кредитів. При переході по цьому пунктів буде відкриватися нова сторінка з інтерфейсом поданим на рисунку нижче:
![image](https://user-images.githubusercontent.com/35197419/71560967-b8050400-2a78-11ea-8f5b-0a39fa9492e6.png)

Список важливих запитань:

1. Поточна кількість записів, яка повертається, близко 3500. Така кількість записів в таблиці одночасно відображених на одному екрані значно погіршить швидкість роботи. Для прискорення роботи потрібно буде добавити пагінацію. Отже, яка кількість записів буде повертатися на продакшені і чи потрібно добавляти пагінацію?

2. Для спрощення сприйняття інформацію, поточну і планову кількість кредитів за годину краще позначити різними кольорами. Для відображення інформації в табличному форматі найкраще використати компонент `ag-grid-angular`, який використовується для цього найчастіше. Я не знайшов існуючої реалізації, при якій в комірці таблиці використовуються різні кольори. Питання наступне, чи потрібно шукати рішення при якому можна буде використати два різних кольори для тексту в одній комірці, чи можна обійтися без кольорів?

**Comment by gzaspa** [comment]
1. Ні, пагінацію робити не обов'язково, тому що неправильна кількість кредитів - це неприпустима ситуація і ВСІ дані речі повинні бути виправлені. Відповідно, спочатку адмін повинен виправити ті численні помилки, які є на початку, один раз, а в подальшому помилки будуть тільки поодинокі. Отже, на сторінці потрібно показувати перші 30 предметів (з повідомленням, що це ще не всі), коли адмін їх вправить і перезавантажить сторінку, з'являться наступні 30 і так можна буде виправити всі.

**Comment by gzaspa** [comment]
2. В даному випадку можна не робити різними кольорами, оскільки буде і так достатньо наглядно.
