### ISSUE TITLE
Адміністратор може знайти всі назви предметів, які являють собою фактично одну назву

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#375]
#228 на бекенді

**Comment by volodymyr-polishchuk** [comment]
Привіт всім!

### Я провів дослідження цієї задачі і виявив наступне:

1. Для отримання списку предметів, які фактично являють собою одну назву потрібно використовувати наступний endpoint:
`GET`
`/course-names/similar`
2. Запит повертає дані в наступному форматі:
```
[
  [
    {
      "id": 9,
      "name": "Web-технології Web-дизайн"
    },
    {
      "id": 10,
      "name": "Web-технології і Web-дизайн"
    },
    {
      "id": 12,
      "name": "Web-технології та Web-дизайн"
    }
  ],
  [
     {
        ... наступний предмет
     }
  ]
]
```
3. Для адміністрування ще *не* існує пункту меню або панелі

### Для вирішення цієї задачі я пропоную зробити наступне:

1. Додати пункт меню, який буде відповідати за адміністрування. Цей пункт меню буде відображатися лише користувачеві з токеном в якому будуть права на адміністрування.
2. Додати підпункт меню в пункті меню адміністрування для відображення схожих предметів. Пропоную назву "Схожі предмети"
3. Створити сервіс для роботи з `/course-names/similar`
4. Додати відображення предметів у вигляді списку за наступним макетом:
![image](https://user-images.githubusercontent.com/35197419/70391954-2529fa00-19e3-11ea-97ed-4f2fb6665ad8.png)

Кожен предмет унікальний предмет буде відображатися окремим елементом в списку. 

Для відображення назви предмету буде обиратися перший варіант зі списку. Під назвою предмету буде відображатися кількість можливих варіантів для предмету. Зправа буде відобратися коротка інформармація про те, як саме предмети відрізняються.

При натиснені на предмет він буде розгортатися. Це досягається за рахунок використання компоненту [Collapse](https://bootstrap-4.ru/docs/4.0/components/collapse/). В розгорнутому вигляді буде відображатися список зі всіх предметів, які схожі. Там буде відображатися назва та ID. 

Додатково можна організувати підсвітку змін відносно першого елемента з допомогою бібліотеки [Text-diff](https://www.npmjs.com/package/text-diff)
