### ISSUE TITLE
Адміністратор може знайти всі назви предметів, що не використовуються ніде, та видалити їх

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#376]
#227 на бекенді

**Comment by volodymyr-polishchuk** [comment]
Привіт всім.

Я дослідив цю задачу і знайшов наступне:

Для задачі вже створенна наступне API:

- Отримання списку назв предметів, які не використовуються:
  `GET`
  `/course-names/unused`
  Відповідь:
  ```
  [
    {
      "id": 1,
      "name": "Валеологія",
      "abbreviation": "",
      "nameEng": ""
    },
    ...
  ]
  ```
- Видалення назв предметів, які не використовуються:
  `DELETE`
  `/course-names`
  Запит:
  ```  
  [id, id2, id3]
  ```

Я пропоную для задачі створити нову сторінку. Для сторінки створити новий підпункт `Очиска назв предметів` в пункті `Адміністрування`.

На сторінці потрібно розмістити елементи для відображення всіх назв предметів, добавити можливість обрати назву предмету, яку потрібно видалити та кнопку для видалення назв предметів.

Сторінку я пропоную створити відповідно до наступного макету:

![image](https://user-images.githubusercontent.com/35197419/72664145-06b41700-3a03-11ea-9949-8476aeb3de7f.png)

**Comment by gzaspa** [comment]
Так, все добре
