### ISSUE TITLE
Адміністратор може знайти всі предмети, що не використовуються ніде та видалити їх

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#377]
#226 на бекенді

**Comment by volodymyr-polishchuk** [comment]
Привіт всім.

Я дослідив цю задачу і знайшов наступне:

Для задачі вже створенна наступне API:

- Отримання списку предметів, які не використовуються:
  `GET` 
  `/course/unused` 
  Відповідь:
  ```
  {
    "items": [
      {
        "id": 793,
        "courseName": {
          "id": 97,
          "name": "Валеологія",
          "nameEng": ""
        },
        "semester": 0,
        "knowledgeControl": {
          "id": 2,
          "name": "залік"
        },
        "hours": 50,
        "credits": 1,
        "hoursPerCredit": 30
      },
     {
       ...
     },
     ...
    ],
    "currentPage": 1,
    "totalPages": 57
  }
  ```
- Видалення предметів, які не використовуються:
  `DELETE`
  `/courses`
  Запит:
  ```
  [id, id2, id3]
  ```

Я пропоную для задачі створити нову сторінку. Для сторінки створити новий підпункт `Очиска предметів` в пукнті `Адміністрування`.

На сторінці потрібно розмістити елементи для відображення всіх предметів, добавити можливість обрати предмети, які потрібно видалити та кнопку для видалення предметів. 

Сторінку я пропоную створити відповідно до наступного макету:

![image](https://user-images.githubusercontent.com/35197419/72663925-812f6780-3a00-11ea-827c-06442286729e.png)

Так як API надає можливість отримати дані лише по сторінках, то додавання пагінації обов'язкове.

**Comment by gzaspa** [comment]
Добре
