### ISSUE TITLE
Працівник деканату може замінити призначений для групи предмет на інший (епік #11) 

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-frontend#99]
Дуже важлива функція. Пов'язана вона з тим, що іноді працівники деканату роблять помилки в призначенні предметів або їм дають не зовсім точну інформацію - буває не рідко. Буквально сьогодні бачив кейс - два предмети з різними id, призначені одній групі - розрізняються тільки одним пропуском перед дужкою в кінці назви. Його потрібно замінити на предмет з правильнішою назвою (відповідно, з іншим id). Як це зробити? Зараз варіант такий: видалити предмет з Предметів для груп (відповідно, таблиці courses_for_groups), внести на його місце правильний предмет, перенабрати всі оцінки з цього предмету (course_id в grade же ж інший). Так от потрібно зробити так, щоб оцінки не перенабирати.

**Comment by Allatell** [comment]
Можно при выделении предмета показывать кнопку, при нажатии на которую можно будет заменить предмет, не изменяя оценок для него, может быть оценки предварительно скопировать в какой-то массив отдельный, а потом переписать для нового предмета

**Comment by gzaspa** [comment]
так, при натисненні на цю кнопку потрібно показувати попап-вікно, в якому можна змінити параметри предмету. При цьому можливі 2 варіанти - вибрати інший інснуючий предмет або змінити якийсь із атрибутів існуючого. При натисненні кнопки ОК в цьому вікні потрібно вичитувати courses_for_groups для старого предмету, замінювати там course_id і записувати в базу

**Comment by gzaspa** [comment]
Крім того не забувайте, що потрібно зробити в Предметах для груп автоматичну адаптацію розмірів таблиць до розміру екрану (зараз на великому екрані вони мають жахливий вигляд) та у верхній таблиці показувати кількість кредитів

**Comment by gzaspa** [comment]
Done.
